# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Jan 16 17:16:37 CET 2013
#
#/ usage: waitfor:ssh  --host <> [ --port <22>] [ --user <root>]  --password <password> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --host) rerun_option_check $# $1; HOST=$2 ; shift ;;
            --port) rerun_option_check $# $1; PORT=$2 ; shift ;;
            --user) rerun_option_check $# $1; USER=$2 ; shift ;;
            --password) rerun_option_check $# $1; PASSWORD=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$PORT" ] && PORT="$(rerun_property_get $RERUN_MODULE_DIR/options/port DEFAULT)"
    [ -z "$USER" ] && USER="$(rerun_property_get $RERUN_MODULE_DIR/options/user DEFAULT)"
    [ -z "$PASSWORD" ] && PASSWORD="$(rerun_property_get $RERUN_MODULE_DIR/options/password DEFAULT)"
    # Check required options are set
    [ -z "$HOST" ] && { echo >&2 "missing required option: --host" ; return 2 ; }
    [ -z "$PASSWORD" ] && { echo >&2 "missing required option: --password" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
HOST=
PORT=
USER=
PASSWORD=


